# LWIP DEAFAULT
# TCP_MSL                   60000
# TCPIP_THREAD_STACKSIZE    4096
# MEM_SIZE                  4096
# MEMP_NUM_NETCONN          4
# MEMP_NUM_TCP_PCB          5
# MEMP_NUM_TCP_SEG          16
# MEMP_NUM_NETBUF           2
# LWIP_TCP_KEEPALIVE
# TCP_KEEPIDLE_DEFAULT      5000
# TCP_KEEPINTVL_DEFAULT     75000UL
# TCP_KEEPCNT_DEFAULT       9U

$(info PLATFOM = $(PLATFORM))

CFLAGS += -DMEMP_NUM_NETBUF=32 -DMEMP_NUM_NETCONN=16 -DMEMP_NUM_TCP_PCB=20 -DMEMP_NUM_TCP_SEG=64
CFLAGS += -DLWIP_NETCONN=1 -DLWIP_SO_SNDTIMEO=1 -DLWIP_SO_RCVTIMEO=1

#ifeq ($(PLATFORM),awh575-mf4)
#CFLAGS += -DMEMP_NUM_NETBUF=32 -DMEMP_NUM_NETCONN=16 -DMEMP_NUM_TCP_PCB=20 -DMEMP_NUM_TCP_SEG=64
#else ifeq ($(PLATFORM),awh575-mf4-sdio)
#CFLAGS += -DMEMP_NUM_NETBUF=32 -DMEMP_NUM_NETCONN=16 -DMEMP_NUM_TCP_PCB=20 -DMEMP_NUM_TCP_SEG=64
#endif
